# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

include(CacheLib.pri)

TEMPLATE = lib
TARGET = CacheLib
CONFIG += staticlib

INCLUDEPATH += \
        $$OPENSSL_INC

LIBS += \
        $$OPENSSL_LIB

HEADERS += CacheLib.h
SOURCES += CacheLib.cpp
